services:
  - type: web
    name: nslkdd-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn nslkdd_api.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: FRONTEND_URL
        value: https://your-frontend.vercel.app
